name: pygcam
dependencies:
- flask=0.10.1=py27_1
- configparser=3.5.0=py27_0
- filelock=2.0.6=py27_0
- future=0.16.0=py27_0
- futures=3.0.3=py27_0
- ipyparallel=6.0.2=py27_0
- lxml=3.6.4=py27_0
- numexpr=2.6.2=np112py27_0
- numpy=1.12.1=py27_0
- numpydoc=0.5=py27_1
- pandas=0.20.1=np112py27_0
- scipy=0.19.0=np112py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- six=1.10.0=py27_0
- sphinx=1.5.6=py27_0
- sphinx_rtd_theme=0.2.4=py27_0
- sqlalchemy=1.1.11=py27_0
- pip:
  - dash==0.17.7
  - dash-core-components==0.7.1
  - dash-html-components==0.7.0
  - dash-renderer==0.7.4
  - flask-bcrypt==0.7.1
  - flask-compress==1.4.0
  - flask-cors==3.0.2
  - flask-httpauth==3.2.1
  - flask-restful==0.3.5
  - flask-seasurf==0.2.2
  - flask-sqlalchemy==2.1
  - geopandas==0.3.0
  - ipyparallel==6.0.2
  - salib==1.0.3
  - sphinx-argparse==0.1.17
  - sphinx-better-theme==0.13
  - sphinx-rtd-theme==0.2.4
  - sphinxjp.themes.basicstrap==0.4.3
  - sphinxtrap==0.2.3
  - sqlalchemy-migrate==0.9.2
