from pygcam.plugin import PluginBase

class DiffCommand(PluginBase):
    def __init__(self, subparsers):
        kwargs = {'help' : '''Compute differences between CSV files generated by GCAM batch queries''',
                  'description' : '''A more detailed description'''}
        super(DiffCommand, self).__init__('diff', kwargs, subparsers)

    def addArgs(self):
        pass

    def run(self, args):
        pass


PluginClass = DiffCommand
